apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-145124-rmpd-service
spec:
  selector:
    app: enterprise-system-145124-rmpd
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
